[project]
name = "python-practice"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-re2>=1.1.20251105",
    "pytest-cache>=1.0",
    "setuptools>=70.3.0",
]

[tool.coverage.run]
omit = [
    "tests/*",
    "*/tests/*",
    "*tests/*"
]

[tool.pytest.ini_options]
# Run coverage report for every `uv run pytest`
# This project will remain small, so this is ok.
addopts = "--cov-report=term-missing"
testpaths = ["tests"]

[tool.ruff]
src = ["logfetcher", "tests"]
line-length = 88

[tool.mypy]
# The directories Mypy should type-check
files = ["logfetcher", "tests"]
# Enforce strict type checking across the project
strict = true

# Be slightly more lenient with type checking inside the test suite
[[tool.mypy.overrides]]
module = "tests.*"
strict = false

[tool.pylint.main]
source-roots = ["logfetcher", "tests"]

[tool.pylint.reports]
# Force the score to be printed at the bottom of the output for the pylint badge
score = true
# Enable the full report (equivalent to --reports=y)
reports = true
output-format = "text"

[tool.setuptools]
packages = ["logfetcher"]

[dependency-groups]
dev = [
    "pyfakefs>=6.1.1",
    "pytest>=9.0.2",
    "pytest-cov>=7.0.0",
    "pylint>=3.3.1",
    "genbadge[coverage,tests]>=1.1.1",
]
